# https://bun.sh/docs/runtime/bunfig
[install]
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }

[install.scopes]
"@quedevstudios" = { url = "https://npm.pkg.github.com", token = "$GH_TOKEN" }

[run]
bun = true
shell = "bun"
silent = true
